"""PerfBaseline — 性能 baseline 量測（SD_Improving_08 W5 / ADR-SD08-003 §2.3）。

設計原則（≤ 150 LOC）：
  - 連跑 N 次（預設 MIN_RUNS=20，v1.1 修訂）取 p50 / p95 / p99，避免單次抖動
  - 純 stdlib（time.perf_counter + statistics），零外部相依
  - 與 pytest-benchmark JSON 格式並存（perf_regression_check 解析 benchmark JSON）
  - `.perf_baseline.toml` 為 SSOT；measure() 產出可直接序列化

對應：
  - ADR-SD08-003 §2.3 量測策略（v1.1：samples ≥ 20，原 7）
  - ADR-SD08-003 §2.4 告警閾值（p95 增量 < 15%）
  - ADR-SD08-003 §2.6 Baseline 鎖定（samples ≥ 20 才可寫入）
"""
from __future__ import annotations

import statistics
import subprocess
import sys
import time
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable, Optional

# ADR-SD08-003 v1.1（SD_09 W1）：samples 最小門檻 — < MIN_RUNS 印 warning，不阻塞
MIN_RUNS = 20


def _percentile(samples: list[float], pct: float) -> float:
    if not samples:
        return 0.0
    sorted_s = sorted(samples)
    n = len(sorted_s)
    if n < 20:
        return float(sorted_s[-1])
    idx = max(0, int(pct * n) - 1)
    return float(sorted_s[idx])


def _current_sha() -> str:
    """讀目前 git SHA（短）；失敗回 'unknown'。"""
    try:
        out = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            stderr=subprocess.DEVNULL,
            text=True,
            timeout=5,
        )
        return out.strip() or "unknown"
    except (subprocess.SubprocessError, FileNotFoundError, OSError):
        return "unknown"


@dataclass(frozen=True)
class PerfBaseline:
    """單一場景 baseline 量測結果。

    欄位語意：
      scenario     : 場景識別（snake_case，需對應 .perf_baseline.toml section）
      p50_ms       : 中位數（ms）
      p95_ms       : 95 分位（ms）
      p99_ms       : 99 分位（ms）
      samples      : 連跑次數
      git_sha      : 採集時 git SHA（短）
      captured_at  : ISO8601 UTC timestamp
    """

    scenario: str
    p50_ms: float
    p95_ms: float
    p99_ms: float
    samples: int
    git_sha: str
    captured_at: str

    def to_toml_section(self) -> str:
        """序列化為 TOML section 字串（給 .perf_baseline.toml 寫入用）。"""
        return (
            f"[{self.scenario}]\n"
            f'p50_ms = {self.p50_ms}\n'
            f'p95_ms = {self.p95_ms}\n'
            f'p99_ms = {self.p99_ms}\n'
            f'samples = {self.samples}\n'
            f'git_sha = "{self.git_sha}"\n'
            f'captured_at = "{self.captured_at}"\n'
        )

    def to_dict(self) -> dict:
        return asdict(self)


def measure(
    scenario: str,
    runner: Callable[[], None],
    *,
    runs: int = MIN_RUNS,
    git_sha: Optional[str] = None,
) -> PerfBaseline:
    """連跑 runs 次取 p50/p95/p99（ADR-SD08-003 §2.3 v1.1）。

    Args:
        scenario: 場景識別（snake_case，例：dry_run_e2e）
        runner: 無參數 callable；measure() 反覆呼叫並計時
        runs: 重複次數（預設 MIN_RUNS=20，ADR-SD08-003 v1.1）
        git_sha: 覆寫 git SHA（測試用）；None 時自動讀

    Returns:
        PerfBaseline；可呼叫 .to_toml_section() 寫入 .perf_baseline.toml
    """
    if runs <= 0:
        raise ValueError(f"runs must be > 0, got {runs}")
    if not scenario:
        raise ValueError("scenario must not be empty")
    if runs < MIN_RUNS:
        # ADR-SD08-003 v1.1：< MIN_RUNS 統計噪音偏高；提示但不阻塞
        sys.stderr.write(
            f"::warning::scenario={scenario} samples={runs} < {MIN_RUNS} "
            f"(statistical noise high; baseline lock 應拒絕寫入)\n"
        )

    samples_ms: list[float] = []
    for _ in range(runs):
        start_ns = time.perf_counter_ns()
        runner()
        elapsed_ms = (time.perf_counter_ns() - start_ns) / 1_000_000.0
        samples_ms.append(elapsed_ms)

    return PerfBaseline(
        scenario=scenario,
        p50_ms=round(statistics.median(samples_ms), 3),
        p95_ms=round(_percentile(samples_ms, 0.95), 3),
        p99_ms=round(_percentile(samples_ms, 0.99), 3),
        samples=runs,
        git_sha=git_sha if git_sha is not None else _current_sha(),
        captured_at=datetime.now(timezone.utc).isoformat(timespec="seconds"),
    )


def write_baseline(path: Path, baselines: list[PerfBaseline]) -> None:
    """將多個場景 baseline 寫入 .perf_baseline.toml（覆寫模式）。

    v1.1（ADR-SD08-003 §2.6）：samples < MIN_RUNS 的 baseline 拒絕寫入並印 warning。
    回傳前過濾不合格 baseline；若全被過濾，仍寫一個空檔（保留 header）。
    """
    body = "# Auto-generated by autoclaude.utils.perf_baseline\n"
    body += f"# Lock policy: SD_09 W1 升 samples ≥ {MIN_RUNS} 才可寫入（ADR-SD08-003 v1.1 §2.6）\n\n"
    rejected = [b for b in baselines if b.samples < MIN_RUNS]
    for r in rejected:
        sys.stderr.write(
            f"::warning::baseline rejected: scenario={r.scenario} "
            f"samples={r.samples} < {MIN_RUNS}\n"
        )
    accepted = [b for b in baselines if b.samples >= MIN_RUNS]
    for b in accepted:
        body += b.to_toml_section() + "\n"
    path.write_text(body, encoding="utf-8")


def write_perf_results(path: Path, baselines: list[PerfBaseline]) -> None:
    """SD_09 Pre-W0 audit B-08 修復：將 measure() 結果序列化為 JSON。

    對應 ci.yml perf-baseline-nightly step，餵給 perf_regression_check.py 比對。
    格式：{ scenario_name: { p50_ms, p95_ms, p99_ms, samples, git_sha, captured_at } }
    """
    import json
    payload = {b.scenario: b.to_dict() for b in baselines}
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


__all__ = ["PerfBaseline", "measure", "write_baseline", "write_perf_results"]
